//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg.proto
namespace MsgDef
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PtcC2GReq_Test")]
  public partial class PtcC2GReq_Test : global::ProtoBuf.IExtensible
  {
    public PtcC2GReq_Test() {}
    
    private eMsgType _MsgType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public eMsgType MsgType
    {
      get { return _MsgType; }
      set { _MsgType = value; }
    }
    private int _version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"eMsgType")]
    public enum eMsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgType_PTCGC2GREQ_TEST", Value=1)]
      MsgType_PTCGC2GREQ_TEST = 1
    }
  
}